# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: "3"

services:
  netflix_zuul_api_gateway:
      
    image: netflix_zuul
  
    ports:
      - "8079:8079"

    environment:
        ZIPKIN_BASE_URL: http://192.168.1.16:9411
        EUREKA_SERVER_ZONE: http://192.168.1.16:8761/eureka
                      
       #MONGO DB SERVER DETAILS
      
       # MONGO_HOST: 192.168.1.16
       # MONGO_PORT: 27017
       # MONGO_AUTHENTICATION_DATABASE: admin
       # MONGO_USERNAME: admin
       # MONGO_PASSWORD: password
       # MONGO_DATABASE: books
      
        # RABBIT MQ SERVER DETAILS
        RABBIT_MQ_HOST: 192.168.1.16
        RABBIT_MQ_PORT: 5672
        RABBIT_MQ_USER_NAME: guest
        RABBIT_MQ_PASSWORD: guest
   
    